#!/bin/bash
# Messaging Bridges Setup Script
# Generates .env file and creates data directories
#
# Usage: ./setup.sh

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}Messaging Bridges Setup${NC}"
echo "========================"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Warning: .env file already exists${NC}"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# =====================================================
# Timezone
# =====================================================
echo -e "${BLUE}General Settings${NC}"
echo "-----------------"
read -p "Timezone [America/Costa_Rica]: " timezone
timezone=${timezone:-America/Costa_Rica}

# =====================================================
# WhatsApp Bridge
# =====================================================
echo ""
echo -e "${BLUE}WhatsApp Bridge${NC}"
echo "-----------------"
echo "WhatsApp uses QR code pairing (no API keys needed)."
echo "The QR code will appear in container logs on first run."
read -p "WhatsApp port [3100]: " whatsapp_port
whatsapp_port=${whatsapp_port:-3100}

# =====================================================
# Telegram Bridge
# =====================================================
echo ""
echo -e "${BLUE}Telegram Bridge${NC}"
echo "-----------------"
echo "Get API credentials from https://my.telegram.org/apps"
echo ""

read -p "Telegram API ID: " telegram_api_id
read -p "Telegram API Hash: " telegram_api_hash
read -p "Telegram Phone (with country code, e.g. +506...): " telegram_phone
read -p "Telegram port [8081]: " telegram_port
telegram_port=${telegram_port:-8081}

if [ -z "$telegram_api_id" ] || [ -z "$telegram_api_hash" ]; then
    echo -e "${YELLOW}Warning: Telegram credentials not provided. Telegram bridge will not start.${NC}"
fi

# =====================================================
# Slack Bridge
# =====================================================
echo ""
echo -e "${BLUE}Slack Bridge${NC}"
echo "-----------------"
echo "Create a Slack app at https://api.slack.com/apps"
echo "Enable Socket Mode and install to workspace."
echo ""

read -p "Slack Bot Token (xoxb-...): " slack_bot_token
read -p "Slack App Token (xapp-...): " slack_app_token
read -p "Slack Signing Secret: " slack_signing_secret
read -p "Slack port [3102]: " slack_port
slack_port=${slack_port:-3102}

if [ -z "$slack_bot_token" ] || [ -z "$slack_app_token" ]; then
    echo -e "${YELLOW}Warning: Slack tokens not provided. Slack bridge will not start.${NC}"
fi

# =====================================================
# Auto-update settings
# =====================================================
echo ""
echo -e "${BLUE}Auto-Update Settings${NC}"
echo "---------------------"
echo "When enabled, bridges pull latest code from GitHub on container restart."
read -p "Enable auto-update for all bridges? (y/N): " auto_update
if [ "$auto_update" = "y" ] || [ "$auto_update" = "Y" ]; then
    whatsapp_auto_update="true"
    telegram_auto_update="true"
    slack_auto_update="true"
else
    whatsapp_auto_update="false"
    telegram_auto_update="false"
    slack_auto_update="false"
fi

# =====================================================
# Create data directories
# =====================================================
echo ""
echo -e "${BLUE}Creating data directories...${NC}"

mkdir -p data/whatsapp/db
mkdir -p data/whatsapp/media
mkdir -p data/telegram/session
mkdir -p data/telegram/db
mkdir -p data/telegram/media
mkdir -p data/slack/db
mkdir -p data/slack/media

echo -e "${GREEN}Data directories created${NC}"

# =====================================================
# Generate .env file
# =====================================================
cat > .env << EOF
# Messaging Bridges Configuration
# Generated by setup.sh on $(date)

# =====================================================
# General
# =====================================================
TIMEZONE=${timezone}

# =====================================================
# WhatsApp Bridge (Baileys)
# =====================================================
# Port for WhatsApp HTTP API
WHATSAPP_PORT=${whatsapp_port}
# Pull latest code on container restart
WHATSAPP_AUTO_UPDATE=${whatsapp_auto_update}

# =====================================================
# Telegram Bridge (Telethon)
# =====================================================
# Get from https://my.telegram.org/apps
TELEGRAM_API_ID=${telegram_api_id}
TELEGRAM_API_HASH=${telegram_api_hash}
TELEGRAM_PHONE=${telegram_phone}
# Port for Telegram HTTP API
TELEGRAM_PORT=${telegram_port}
# Pull latest code on container restart
TELEGRAM_AUTO_UPDATE=${telegram_auto_update}

# =====================================================
# Slack Bridge (Bolt.js)
# =====================================================
# Get from https://api.slack.com/apps
SLACK_BOT_TOKEN=${slack_bot_token}
SLACK_APP_TOKEN=${slack_app_token}
SLACK_SIGNING_SECRET=${slack_signing_secret}
# Port for Slack HTTP API
SLACK_PORT=${slack_port}
# Pull latest code on container restart
SLACK_AUTO_UPDATE=${slack_auto_update}
EOF

echo ""
echo -e "${GREEN}Configuration saved to .env${NC}"
echo ""
echo "Data directory structure:"
echo "  data/"
echo "  ├── whatsapp/"
echo "  │   ├── db/       (SQLite databases)"
echo "  │   └── media/    (Downloaded media files)"
echo "  ├── telegram/"
echo "  │   ├── session/  (Telethon session file)"
echo "  │   ├── db/       (SQLite databases)"
echo "  │   └── media/    (Downloaded media files)"
echo "  └── slack/"
echo "      ├── db/       (SQLite databases)"
echo "      └── media/    (Downloaded media files)"
echo ""
echo -e "${YELLOW}Note: WhatsApp auth is stored in a Docker named volume (whatsapp_auth_info)${NC}"
echo ""
echo "Start the stack with:"
echo -e "  ${GREEN}docker-compose up -d${NC}"
echo ""
echo "View WhatsApp QR code (first run):"
echo -e "  ${GREEN}docker logs -f whatsapp-bridge${NC}"
